### ISSUE TITLE
Broken link to dataset in Arxiv Paper

### ISSUE THREAD

**Issue by ozcelikfu** [dkucuk/Tweet-Dataset-NER-SD#1]
Link in Arxiv paper to this dataset is splitted in two row. It does not working correctly when it is clicked. It might be good to fix it since paper is about the dataset, people can be confused and think that dataset is not uploaded yet when they see error in github page

**Comment by dkucuk** [comment]
A new version of the paper is uploaded to arxiv.org, in which the URLs are fixed, thank you.
